name: Check if you are able to merge

on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set-up Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: yarn
      - run: yarn test
  acknowledgment:
    needs: build
    name: Hello new contributor
    runs-on: ubuntu-latest
    steps:
      - uses: thollander/actions-comment-pull-request@master
        with:
          message: "Hey, thank you for opening your Pull Request !"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
